/**
 * ============================================
 * PAGE CONTENT DATA
 * ============================================
 * All structured content for pages lives here.
 * Edit these arrays/objects to customize the template content.
 *
 * Replace placeholder images in src/assets/ with your own.
 */

export const site = {
  url: 'https://jmcip.github.io',
  meta: {
    title: 'Jose Manuel Cipagauta | Engineering Student',
    description:
      'Portfolio example: shipping reliable web products with clear architecture, tests, and delivery practices.',
  },
  hero: {
    name: 'Jose Manuel Cipagauta',
    role: 'Systems Engineering Student',
    tagline:
      'Building modern web applications while learning, creating, and growing as a Full Stack Developer.',
    contact:
      'Open to internships, academic collaborations, and opportunities to gain professional experience.',
    avatarSrc: '/favicon.svg',
    avatarAlt: 'Jose Manuel Cipagauta',
  },
about: {
  paragraphs: [
    'I am a fourth-semester Systems Engineering student passionate about software development and problem-solving. I enjoy building web applications that combine clean design with efficient functionality while continuously learning new technologies.',
    'Throughout my academic projects, I have worked with both frontend and backend technologies, focusing on writing organized, maintainable, and scalable code. Every project helps me strengthen my technical skills and gain practical development experience.',
    {
      heading: 'Areas of Interest',
      bullets: [
        'Full Stack Web Development',
        'Backend Development with Java and Spring Boot',
        'Frontend Development with Angular',
      ],
    },
    {
      heading: 'Technologies',
      techItems: [
        'Java',
        'Spring Boot',
        'Angular',
        'TypeScript',
        'JavaScript',
        'HTML',
        'CSS',
        'GitHub',
      ],
    },
  ],
},
  experiences: [
    {
      period: '2026',
      title: 'DetectIA',
      company: 'Academic Full Stack Project',
      summary:
        'Developed a Full Stack web application that analyzes images, videos, audio, and PDF files to estimate whether their content was generated by artificial intelligence through an intuitive and responsive interface.',
      highlights: [
        'Designed and implemented a responsive frontend using Angular and TypeScript.',
        'Developed RESTful APIs with Spring Boot and Java to process and manage file analysis.',
        'Integrated support for multiple file formats, including images, videos, audio, and PDF documents.',
        'Applied a modular architecture to improve maintainability and scalability throughout the application.',
      ],
      tech: ['Angular','TypeScript','Spring Boot','Java','REST API','GitHub', 'HTML','CSS'],
    },
    {
      period: '2026',
      title: 'Package Delivery Management System',
      company: 'Academic Java Project',
      summary:
        'Developed a desktop application for managing package deliveries, allowing users to register shipments, track delivery information, and organize logistics through an intuitive graphical interface.',
      highlights: [
        'Designed and implemented the application using Java and Object-Oriented Programming principles.',
        'Built a desktop user interface with Java Swing to manage package registration and shipment tracking.',
        'Applied a modular architecture to separate business logic from the presentation layer.',
        'Implemented data validation and management features to ensure accurate shipment records.',
      ],
      tech: [
        'Java',
        'Spring Boot',
        'Angular',
        'TypeScript',
        'HTML',
        'CSS',
        'GitHub',
      ],
    },
    {
      period: '2023',
      title: 'UI Engineer',
      company: 'Orbital Creative',
      summary:
        'Created an interactive product showcase with a clean visual system and accessible component library.',
      highlights: [
        'Built a flexible project card system for content updates without code changes',
        'Improved brand consistency with typography, color, and motion guidelines',
        'Added testing and quality checks for cross-device UI fidelity',
      ],
      tech: ['Astro', 'Tailwind CSS', 'JavaScript', 'Node', 'Vitest'],
    },
  ],
  featuredProjects: [
    {
      title: 'Lumen Studio Website',
      period: '2025',
      summary: 'Built a polished portfolio experience with accessible UI, motion-led interactions, and reusable components.',
      solution: 'Designed a modular component system with Astro and Tailwind CSS, ensuring consistent brand experience across all breakpoints.',
      impact: 'Achieved sub-1s page load metrics and 95+ Lighthouse scores through optimized asset delivery and lazy loading strategies.',
      image: 'astro-01.webp',
      imageAlt: 'Lumen Studio website showcase',
      techCategories: [
        {
          category: 'Frontend',
          items: ['TypeScript', 'Astro', 'Tailwind CSS', 'Responsive Design'],
        },
        {
          category: 'Performance',
          items: ['Asset Optimization', 'Lazy Loading', 'Image CDN'],
        },
      ],
    },
  ],

  projectArchivePage: {
    title: 'All projects',
    description: 'Project archive: dates, roles, and technologies across representative engagements.',
    intro: 'A concise archive of engagements and representative work.',
  },
  projectArchive: [
    { date: '2025', project: 'Design system rollout', role: 'Frontend', techStack: 'Astro, CSS, Storybook' },
    { date: '2024', project: 'Checkout reliability', role: 'Full-stack', techStack: 'TypeScript, Postgres, Redis' },
    { date: '2024', project: 'Auth hardening', role: 'Backend', techStack: 'OAuth2, JWT, rate limits' },
    { date: '2023', project: 'Analytics pipeline', role: 'Data', techStack: 'SQL, dbt, warehouse' },
    { date: '2023', project: 'Mobile web refresh', role: 'Frontend', techStack: 'HTML, CSS, a11y audits' },
  ],
  contact: {
    email: 'josemanuelcipa2006@gmail.com',
    github: 'https://github.com/JMCip',
    linkedin: 'www.linkedin.com/in/jose-manuel-cipagauta-toro-7b69b2349',
  },
} as const;

export type ProjectArchiveRow = (typeof site.projectArchive)[number];
export type FeaturedProject = (typeof site.featuredProjects)[number];
